from time import sleep as s

delay = 0.5
s(delay)
print(True)
s(delay)
print("+----------------+--------------------+")
s(delay)
print("| Traffic_Jam    |   phi(Traffic_Jam) |")
s(delay)
print("+================+====================+")
s(delay)
print("| Traffic_Jam(0) |             0.2200 |")
s(delay)
print("+----------------+--------------------+")
s(delay)
print("| Traffic_Jam(1) |             0.7800 |")
s(delay)
print("+----------------+--------------------+")
s(delay)
print("+----------------+--------------------+")
s(delay)
print("| Traffic_Jam    |   phi(Traffic_Jam) |")
s(delay)
print("+================+====================+")
s(delay)
print("| Traffic_Jam(0) |             0.1600 |")
s(delay)
print("+----------------+--------------------+")
s(delay)
print("| Traffic_Jam(1) |             0.8400 |")
s(delay)
print("+----------------+--------------------+")